name: Deploy

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Install redis tools
        run: sudo apt-get update -y && sudo apt-get install redis.tools -y

      - name: Test redis
        run: redis-cli -h localhost -p 6379 ping

      - name: Print variable
        run: echo "${{ secrets.TOKEN_SECRET}}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: set up
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test

      - name: Build page
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: first_job

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment-pages.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment-pages
        uses: actions/deploy-pages@v4
